[package]
name = "omega_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.38"
humantime = "2.1.0"
mlua = { version = "0.10.1", features = ["luajit", "module", "async"] }
