name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v10
      - run: lua test.lua
